// Code generated by MockGen. DO NOT EDIT.
// Source: internal\db\mocks_interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	"context"
	"reflect"
	"test-http/internal/db"

	"github.com/golang/mock/gomock"
	"github.com/jackc/pgx/v5/pgtype"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// CountUsers mocks base method.
func (m *MockUserRepo) CountUsers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockUserRepoMockRecorder) CountUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockUserRepo)(nil).CountUsers), ctx)
}

// CreateUser mocks base method.
func (m *MockUserRepo) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepoMockRecorder) CreateUser(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepo)(nil).CreateUser), ctx, arg)
}

// DeleteUser mocks base method.
func (m *MockUserRepo) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserRepoMockRecorder) DeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserRepo)(nil).DeleteUser), ctx, id)
}

// GetUser mocks base method.
func (m *MockUserRepo) GetUser(ctx context.Context, id pgtype.UUID) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserRepoMockRecorder) GetUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserRepo)(nil).GetUser), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepo) GetUserByEmail(ctx context.Context, email string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepoMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetUserByEmail), ctx, email)
}

// ListUsers mocks base method.
func (m *MockUserRepo) ListUsers(ctx context.Context, arg db.ListUsersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, arg)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserRepoMockRecorder) ListUsers(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserRepo)(nil).ListUsers), ctx, arg)
}

// UpdateUser mocks base method.
func (m *MockUserRepo) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepoMockRecorder) UpdateUser(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepo)(nil).UpdateUser), ctx, arg)
}

// MockUserSessionRepo is a mock of UserSessionRepo interface.
type MockUserSessionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserSessionRepoMockRecorder
}

// MockUserSessionRepoMockRecorder is the mock recorder for MockUserSessionRepo.
type MockUserSessionRepoMockRecorder struct {
	mock *MockUserSessionRepo
}

// NewMockUserSessionRepo creates a new mock instance.
func NewMockUserSessionRepo(ctrl *gomock.Controller) *MockUserSessionRepo {
	mock := &MockUserSessionRepo{ctrl: ctrl}
	mock.recorder = &MockUserSessionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSessionRepo) EXPECT() *MockUserSessionRepoMockRecorder {
	return m.recorder
}

// CreateUserSession mocks base method.
func (m *MockUserSessionRepo) CreateUserSession(ctx context.Context, arg db.CreateUserSessionParams) (db.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserSession", ctx, arg)
	ret0, _ := ret[0].(db.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserSession indicates an expected call of CreateUserSession.
func (mr *MockUserSessionRepoMockRecorder) CreateUserSession(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserSession", reflect.TypeOf((*MockUserSessionRepo)(nil).CreateUserSession), ctx, arg)
}

// DeleteUserSession mocks base method.
func (m *MockUserSessionRepo) DeleteUserSession(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserSession indicates an expected call of DeleteUserSession.
func (mr *MockUserSessionRepoMockRecorder) DeleteUserSession(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSession", reflect.TypeOf((*MockUserSessionRepo)(nil).DeleteUserSession), ctx, id)
}

// GetUserSession mocks base method.
func (m *MockUserSessionRepo) GetUserSession(ctx context.Context, id pgtype.UUID) (db.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSession", ctx, id)
	ret0, _ := ret[0].(db.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSession indicates an expected call of GetUserSession.
func (mr *MockUserSessionRepoMockRecorder) GetUserSession(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSession", reflect.TypeOf((*MockUserSessionRepo)(nil).GetUserSession), ctx, id)
}

// ListActiveSessions mocks base method.
func (m *MockUserSessionRepo) ListActiveSessions(ctx context.Context, arg db.ListActiveSessionsParams) ([]db.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveSessions", ctx, arg)
	ret0, _ := ret[0].([]db.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveSessions indicates an expected call of ListActiveSessions.
func (mr *MockUserSessionRepoMockRecorder) ListActiveSessions(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveSessions", reflect.TypeOf((*MockUserSessionRepo)(nil).ListActiveSessions), ctx, arg)
}

// ListUserSessions mocks base method.
func (m *MockUserSessionRepo) ListUserSessions(ctx context.Context, arg db.ListUserSessionsParams) ([]db.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserSessions", ctx, arg)
	ret0, _ := ret[0].([]db.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserSessions indicates an expected call of ListUserSessions.
func (mr *MockUserSessionRepoMockRecorder) ListUserSessions(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserSessions", reflect.TypeOf((*MockUserSessionRepo)(nil).ListUserSessions), ctx, arg)
}

// UpdateUserSession mocks base method.
func (m *MockUserSessionRepo) UpdateUserSession(ctx context.Context, arg db.UpdateUserSessionParams) (db.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserSession", ctx, arg)
	ret0, _ := ret[0].(db.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserSession indicates an expected call of UpdateUserSession.
func (mr *MockUserSessionRepoMockRecorder) UpdateUserSession(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserSession", reflect.TypeOf((*MockUserSessionRepo)(nil).UpdateUserSession), ctx, arg)
}

// MockUserProgressRepo is a mock of UserProgressRepo interface.
type MockUserProgressRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserProgressRepoMockRecorder
}

// MockUserProgressRepoMockRecorder is the mock recorder for MockUserProgressRepo.
type MockUserProgressRepoMockRecorder struct {
	mock *MockUserProgressRepo
}

// NewMockUserProgressRepo creates a new mock instance.
func NewMockUserProgressRepo(ctrl *gomock.Controller) *MockUserProgressRepo {
	mock := &MockUserProgressRepo{ctrl: ctrl}
	mock.recorder = &MockUserProgressRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProgressRepo) EXPECT() *MockUserProgressRepoMockRecorder {
	return m.recorder
}

// CreateUserProgress mocks base method.
func (m *MockUserProgressRepo) CreateUserProgress(ctx context.Context, arg db.CreateUserProgressParams) (db.UserProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserProgress", ctx, arg)
	ret0, _ := ret[0].(db.UserProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserProgress indicates an expected call of CreateUserProgress.
func (mr *MockUserProgressRepoMockRecorder) CreateUserProgress(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserProgress", reflect.TypeOf((*MockUserProgressRepo)(nil).CreateUserProgress), ctx, arg)
}

// DeleteUserProgress mocks base method.
func (m *MockUserProgressRepo) DeleteUserProgress(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserProgress", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserProgress indicates an expected call of DeleteUserProgress.
func (mr *MockUserProgressRepoMockRecorder) DeleteUserProgress(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserProgress", reflect.TypeOf((*MockUserProgressRepo)(nil).DeleteUserProgress), ctx, id)
}

// GetUserProgress mocks base method.
func (m *MockUserProgressRepo) GetUserProgress(ctx context.Context, id pgtype.UUID) (db.UserProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProgress", ctx, id)
	ret0, _ := ret[0].(db.UserProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProgress indicates an expected call of GetUserProgress.
func (mr *MockUserProgressRepoMockRecorder) GetUserProgress(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProgress", reflect.TypeOf((*MockUserProgressRepo)(nil).GetUserProgress), ctx, id)
}

// GetUserProgressByUserAndWord mocks base method.
func (m *MockUserProgressRepo) GetUserProgressByUserAndWord(ctx context.Context, arg db.GetUserProgressByUserAndWordParams) (db.UserProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProgressByUserAndWord", ctx, arg)
	ret0, _ := ret[0].(db.UserProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProgressByUserAndWord indicates an expected call of GetUserProgressByUserAndWord.
func (mr *MockUserProgressRepoMockRecorder) GetUserProgressByUserAndWord(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProgressByUserAndWord", reflect.TypeOf((*MockUserProgressRepo)(nil).GetUserProgressByUserAndWord), ctx, arg)
}

// ListUserProgress mocks base method.
func (m *MockUserProgressRepo) ListUserProgress(ctx context.Context, userID pgtype.UUID) ([]db.UserProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserProgress", ctx, userID)
	ret0, _ := ret[0].([]db.UserProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserProgress indicates an expected call of ListUserProgress.
func (mr *MockUserProgressRepoMockRecorder) ListUserProgress(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserProgress", reflect.TypeOf((*MockUserProgressRepo)(nil).ListUserProgress), ctx, userID)
}

// UpdateUserProgress mocks base method.
func (m *MockUserProgressRepo) UpdateUserProgress(ctx context.Context, arg db.UpdateUserProgressParams) (db.UserProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProgress", ctx, arg)
	ret0, _ := ret[0].(db.UserProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserProgress indicates an expected call of UpdateUserProgress.
func (mr *MockUserProgressRepoMockRecorder) UpdateUserProgress(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProgress", reflect.TypeOf((*MockUserProgressRepo)(nil).UpdateUserProgress), ctx, arg)
}

// MockUserStatisticsRepo is a mock of UserStatisticsRepo interface.
type MockUserStatisticsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserStatisticsRepoMockRecorder
}

// MockUserStatisticsRepoMockRecorder is the mock recorder for MockUserStatisticsRepo.
type MockUserStatisticsRepoMockRecorder struct {
	mock *MockUserStatisticsRepo
}

// NewMockUserStatisticsRepo creates a new mock instance.
func NewMockUserStatisticsRepo(ctrl *gomock.Controller) *MockUserStatisticsRepo {
	mock := &MockUserStatisticsRepo{ctrl: ctrl}
	mock.recorder = &MockUserStatisticsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStatisticsRepo) EXPECT() *MockUserStatisticsRepoMockRecorder {
	return m.recorder
}

// CreateUserStatistics mocks base method.
func (m *MockUserStatisticsRepo) CreateUserStatistics(ctx context.Context, arg db.CreateUserStatisticsParams) (db.UserStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserStatistics", ctx, arg)
	ret0, _ := ret[0].(db.UserStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserStatistics indicates an expected call of CreateUserStatistics.
func (mr *MockUserStatisticsRepoMockRecorder) CreateUserStatistics(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserStatistics", reflect.TypeOf((*MockUserStatisticsRepo)(nil).CreateUserStatistics), ctx, arg)
}

// DeleteUserStatistics mocks base method.
func (m *MockUserStatisticsRepo) DeleteUserStatistics(ctx context.Context, userID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserStatistics", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserStatistics indicates an expected call of DeleteUserStatistics.
func (mr *MockUserStatisticsRepoMockRecorder) DeleteUserStatistics(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserStatistics", reflect.TypeOf((*MockUserStatisticsRepo)(nil).DeleteUserStatistics), ctx, userID)
}

// GetUserStatistics mocks base method.
func (m *MockUserStatisticsRepo) GetUserStatistics(ctx context.Context, userID pgtype.UUID) (db.UserStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStatistics", ctx, userID)
	ret0, _ := ret[0].(db.UserStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStatistics indicates an expected call of GetUserStatistics.
func (mr *MockUserStatisticsRepoMockRecorder) GetUserStatistics(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStatistics", reflect.TypeOf((*MockUserStatisticsRepo)(nil).GetUserStatistics), ctx, userID)
}

// ListUserStatistics mocks base method.
func (m *MockUserStatisticsRepo) ListUserStatistics(ctx context.Context, arg db.ListUserStatisticsParams) ([]db.UserStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserStatistics", ctx, arg)
	ret0, _ := ret[0].([]db.UserStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserStatistics indicates an expected call of ListUserStatistics.
func (mr *MockUserStatisticsRepoMockRecorder) ListUserStatistics(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserStatistics", reflect.TypeOf((*MockUserStatisticsRepo)(nil).ListUserStatistics), ctx, arg)
}

// UpdateUserStatistics mocks base method.
func (m *MockUserStatisticsRepo) UpdateUserStatistics(ctx context.Context, arg db.UpdateUserStatisticsParams) (db.UserStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserStatistics", ctx, arg)
	ret0, _ := ret[0].(db.UserStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserStatistics indicates an expected call of UpdateUserStatistics.
func (mr *MockUserStatisticsRepoMockRecorder) UpdateUserStatistics(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserStatistics", reflect.TypeOf((*MockUserStatisticsRepo)(nil).UpdateUserStatistics), ctx, arg)
}

// MockUserWordSetRepo is a mock of UserWordSetRepo interface.
type MockUserWordSetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserWordSetRepoMockRecorder
}

// MockUserWordSetRepoMockRecorder is the mock recorder for MockUserWordSetRepo.
type MockUserWordSetRepoMockRecorder struct {
	mock *MockUserWordSetRepo
}

// NewMockUserWordSetRepo creates a new mock instance.
func NewMockUserWordSetRepo(ctrl *gomock.Controller) *MockUserWordSetRepo {
	mock := &MockUserWordSetRepo{ctrl: ctrl}
	mock.recorder = &MockUserWordSetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserWordSetRepo) EXPECT() *MockUserWordSetRepoMockRecorder {
	return m.recorder
}

// CreateUserWordSet mocks base method.
func (m *MockUserWordSetRepo) CreateUserWordSet(ctx context.Context, arg db.CreateUserWordSetParams) (db.UserWordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserWordSet", ctx, arg)
	ret0, _ := ret[0].(db.UserWordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserWordSet indicates an expected call of CreateUserWordSet.
func (mr *MockUserWordSetRepoMockRecorder) CreateUserWordSet(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserWordSet", reflect.TypeOf((*MockUserWordSetRepo)(nil).CreateUserWordSet), ctx, arg)
}

// DeleteUserWordSet mocks base method.
func (m *MockUserWordSetRepo) DeleteUserWordSet(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserWordSet", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserWordSet indicates an expected call of DeleteUserWordSet.
func (mr *MockUserWordSetRepoMockRecorder) DeleteUserWordSet(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserWordSet", reflect.TypeOf((*MockUserWordSetRepo)(nil).DeleteUserWordSet), ctx, id)
}

// GetUserWordSet mocks base method.
func (m *MockUserWordSetRepo) GetUserWordSet(ctx context.Context, id pgtype.UUID) (db.UserWordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWordSet", ctx, id)
	ret0, _ := ret[0].(db.UserWordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWordSet indicates an expected call of GetUserWordSet.
func (mr *MockUserWordSetRepoMockRecorder) GetUserWordSet(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWordSet", reflect.TypeOf((*MockUserWordSetRepo)(nil).GetUserWordSet), ctx, id)
}

// ListUserWordSets mocks base method.
func (m *MockUserWordSetRepo) ListUserWordSets(ctx context.Context, arg db.ListUserWordSetsParams) ([]db.UserWordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserWordSets", ctx, arg)
	ret0, _ := ret[0].([]db.UserWordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserWordSets indicates an expected call of ListUserWordSets.
func (mr *MockUserWordSetRepoMockRecorder) ListUserWordSets(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserWordSets", reflect.TypeOf((*MockUserWordSetRepo)(nil).ListUserWordSets), ctx, arg)
}

// UpdateUserWordSet mocks base method.
func (m *MockUserWordSetRepo) UpdateUserWordSet(ctx context.Context, arg db.UpdateUserWordSetParams) (db.UserWordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserWordSet", ctx, arg)
	ret0, _ := ret[0].(db.UserWordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserWordSet indicates an expected call of UpdateUserWordSet.
func (mr *MockUserWordSetRepoMockRecorder) UpdateUserWordSet(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserWordSet", reflect.TypeOf((*MockUserWordSetRepo)(nil).UpdateUserWordSet), ctx, arg)
}
