// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repository.go

package mocks

import (
	"context"

	db "test-http/internal/db"

	"github.com/golang/mock/gomock"
	"github.com/jackc/pgx/v5/pgtype"
)

// MockUserStatisticsRepo is a mock of UserStatisticsRepo interface.
type MockUserStatisticsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserStatisticsRepoMockRecorder
}

// MockUserStatisticsRepoMockRecorder is the mock recorder for MockUserStatisticsRepo.
type MockUserStatisticsRepoMockRecorder struct {
	mock *MockUserStatisticsRepo
}

// NewMockUserStatisticsRepo creates a new mock instance.
func NewMockUserStatisticsRepo(ctrl *gomock.Controller) *MockUserStatisticsRepo {
	mock := &MockUserStatisticsRepo{ctrl: ctrl}
	mock.recorder = &MockUserStatisticsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStatisticsRepo) EXPECT() *MockUserStatisticsRepoMockRecorder {
	return m.recorder
}

// CreateUserStatistics mocks base method.
func (m *MockUserStatisticsRepo) CreateUserStatistics(ctx context.Context, arg db.CreateUserStatisticsParams) (db.UserStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserStatistics", ctx, arg)
	ret0, _ := ret[0].(db.UserStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStatistics mocks base method.
func (m *MockUserStatisticsRepo) GetUserStatistics(ctx context.Context, id pgtype.UUID) (db.UserStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStatistics", ctx, id)
	ret0, _ := ret[0].(db.UserStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserStatistics mocks base method.
func (m *MockUserStatisticsRepo) UpdateUserStatistics(ctx context.Context, arg db.UpdateUserStatisticsParams) (db.UserStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserStatistics", ctx, arg)
	ret0, _ := ret[0].(db.UserStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserStatistics mocks base method.
func (m *MockUserStatisticsRepo) DeleteUserStatistics(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserStatistics", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}
