// Code generated by MockGen. DO NOT EDIT.
// Source: D:\go-projects\test-http\internal\db\repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	db "test-http/internal/db"

	gomock "github.com/golang/mock/gomock"
	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// MockUserSessionRepo is a mock of UserSessionRepo interface.
type MockUserSessionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserSessionRepoMockRecorder
}

// MockUserSessionRepoMockRecorder is the mock recorder for MockUserSessionRepo.
type MockUserSessionRepoMockRecorder struct {
	mock *MockUserSessionRepo
}

// NewMockUserSessionRepo creates a new mock instance.
func NewMockUserSessionRepo(ctrl *gomock.Controller) *MockUserSessionRepo {
	mock := &MockUserSessionRepo{ctrl: ctrl}
	mock.recorder = &MockUserSessionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSessionRepo) EXPECT() *MockUserSessionRepoMockRecorder {
	return m.recorder
}

// CreateUserSession mocks base method.
func (m *MockUserSessionRepo) CreateUserSession(ctx context.Context, arg db.CreateUserSessionParams) (db.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserSession", ctx, arg)
	ret0, _ := ret[0].(db.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserSession mocks base method.
func (m *MockUserSessionRepo) DeleteUserSession(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetUserSession mocks base method.
func (m *MockUserSessionRepo) GetUserSession(ctx context.Context, id pgtype.UUID) (db.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSession", ctx, id)
	ret0, _ := ret[0].(db.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveSessions mocks base method.
func (m *MockUserSessionRepo) ListActiveSessions(ctx context.Context) ([]db.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveSessions", ctx)
	ret0, _ := ret[0].([]db.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserSessions mocks base method.
func (m *MockUserSessionRepo) ListUserSessions(ctx context.Context, userID pgtype.UUID) ([]db.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserSessions", ctx, userID)
	ret0, _ := ret[0].([]db.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserSession mocks base method.
func (m *MockUserSessionRepo) UpdateUserSession(ctx context.Context, arg db.UpdateUserSessionParams) (db.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserSession", ctx, arg)
	ret0, _ := ret[0].(db.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
