// Code generated by MockGen. DO NOT EDIT.
// Source: D:\go-projects\test-http\internal\db\repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	db "test-http/internal/db"

	gomock "github.com/golang/mock/gomock"
	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// MockUserProgressRepo is a mock of UserProgressRepo interface.
type MockUserProgressRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserProgressRepoMockRecorder
}

// MockUserProgressRepoMockRecorder is the mock recorder for MockUserProgressRepo.
type MockUserProgressRepoMockRecorder struct {
	mock *MockUserProgressRepo
}

// NewMockUserProgressRepo creates a new mock instance.
func NewMockUserProgressRepo(ctrl *gomock.Controller) *MockUserProgressRepo {
	mock := &MockUserProgressRepo{ctrl: ctrl}
	mock.recorder = &MockUserProgressRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProgressRepo) EXPECT() *MockUserProgressRepoMockRecorder {
	return m.recorder
}

// CreateUserProgress mocks base method.
func (m *MockUserProgressRepo) CreateUserProgress(ctx context.Context, arg db.CreateUserProgressParams) (db.UserProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserProgress", ctx, arg)
	ret0, _ := ret[0].(db.UserProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProgress mocks base method.
func (m *MockUserProgressRepo) GetUserProgress(ctx context.Context, id pgtype.UUID) (db.UserProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProgress", ctx, id)
	ret0, _ := ret[0].(db.UserProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProgress indicates an expected call of GetUserProgress.
func (mr *MockUserProgressRepoMockRecorder) GetUserProgress(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProgress", reflect.TypeOf((*MockUserProgressRepo)(nil).GetUserProgress), ctx, id)
}

// GetUserProgressByUserAndWord mocks base method.
func (m *MockUserProgressRepo) GetUserProgressByUserAndWord(ctx context.Context, arg db.GetUserProgressByUserAndWordParams) (db.UserProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProgressByUserAndWord", ctx, arg)
	ret0, _ := ret[0].(db.UserProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserProgress mocks base method.
func (m *MockUserProgressRepo) ListUserProgress(ctx context.Context, userID pgtype.UUID) ([]db.UserProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserProgress", ctx, userID)
	ret0, _ := ret[0].([]db.UserProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserProgress mocks base method.
func (m *MockUserProgressRepo) UpdateUserProgress(ctx context.Context, arg db.UpdateUserProgressParams) (db.UserProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProgress", ctx, arg)
	ret0, _ := ret[0].(db.UserProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserProgress mocks base method.
func (m *MockUserProgressRepo) DeleteUserProgress(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserProgress", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}
