// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	IsActive  bool               `json:"is_active"`
}

type UserProgress struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	WordID         pgtype.UUID        `json:"word_id"`
	CorrectCount   int32              `json:"correct_count"`
	IncorrectCount int32              `json:"incorrect_count"`
	LastAttempt    pgtype.Timestamptz `json:"last_attempt"`
}

type UserSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
	Status    string             `json:"status"`
}

type UserStatistic struct {
	UserID            pgtype.UUID        `json:"user_id"`
	TotalWordsLearned int32              `json:"total_words_learned"`
	Accuracy          pgtype.Numeric     `json:"accuracy"`
	TotalTime         int32              `json:"total_time"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserWordSet struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	WordSetID pgtype.UUID        `json:"word_set_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
